name: ollama_gtk_client
description: "a flutter app build with ubuntu style"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  yaru: ^5.3.2
  safe_change_notifier: ^0.4.0
  provider: ^6.1.2
  handy_window: ^0.4.0
  ollama_dart: ^0.2.2
  bot_toast: ^4.1.3
  flutter_distributor: ^0.4.5
  flutter_markdown: ^0.7.4+1
  gtk: ^2.1.0
  xdg_desktop_portal:
    path: lib/src/xdg_desktop_portal.dart
  ffi: ^2.1.3
  platform_linux: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: YaruIcons
      fonts:
        - asset: assets/yaru_icons.otf
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-Regular.ttf
        - asset: assets/fonts/MiSans-Demibold.ttf